### ISSUE TITLE
Problem with LabVIEW Position Closed Loop example.

### ISSUE THREAD

**Issue by wickersigpi1001** [CrossTheRoadElec/FRC-Examples#2]
I have found an issue with the Position Closed example in TeleOp there is a case structure that switches true when button 4 is pressed. The purpose seems to be to set the current position to the absolute position from the Pulse width reading. As stated the code takes the last 12 bits from the PW reading and uses that Encoder (0-4096) value and writes it into the Sensor Position parameter of the CANTalonSRX_SetParameter.vi. 
![image](https://cloud.githubusercontent.com/assets/17650395/13534744/4e9a7f54-e1fc-11e5-8fb5-959080e6def4.png)

If you dig into the SetParameter.vi the position parameter assumes units of rotation not encoder counts.

![image](https://cloud.githubusercontent.com/assets/17650395/13534853/cae29b0a-e1fc-11e5-9f37-a038e07746f8.png)

so the code as written will take the 12 bit encoder value and multiply it by 4096 writing a unitended value as the position.

We are finding the CANSRX LabVIEW drivers confusing when trying to do position because of the inconsistency of the position value inputs. Sometimes the position input is in encoder counts and other times they require rotations.

To assist in clarity I would recommend that you put the unit names in all of the Enum selections. Example: "Position" selection would be changed to "Position (Encoder Counts)" 

![image](https://cloud.githubusercontent.com/assets/17650395/13535443/d0cea1d2-e1ff-11e5-9fb4-9bdad61018c8.png)

In addition you could also add "Position (Rotations) to the enum list which give the user the ability to choose the unit type.

**Comment by ozrien** [comment]
The units are not constant, they are sensor dependent.  Depending on the configuration the units are in rotations, or in sensor native units.  Please read section 17.2 and and 21.25 (LabVIEW) in the Talon SRX Software Reference Manual.

**Comment by wickersigpi1001** [comment]
What part of my comment are you disputing?

In this example the WPI_CANTalonSRX_SetParameter.vi  uses Parameter input selection for "Sensor Position" #73 and is assuming rotation as the input. It converts this input into encoder counts before sending the data to the CAN.  

If CTR Magnetic Enc (Relative) is selected as the sensor then the input value will be multiplied by 4096.

The code is extracting the last 12 bits from the Pulse Width value.
The comment states that "This leaves us with a value within [0-4095]
This value is then wired into the value input thus you get a 0-4095 value multiplied by 4096 that is then written to the CAN Bus as the position value. 

This is not the intended value and needs to be corrected.

**Comment by wickersigpi1001** [comment]
So I did some further investigation into the LabVIEW CAN Talon SRX vis found in the WPI lib and discovered that  the WPI_CANTalonSRX_SetSensorPosition also has a similar issue for CTR Magnetic Encoders.

![image](https://cloud.githubusercontent.com/assets/17650395/13550633/c8550346-e2e7-11e5-8b42-32041569bd34.png)

The top image is the block diagram for the WPI_CANTalonSRX_SetSensorPosition.vi and we see that the "New Sensor Position" Is being scaled to "Native Units" and then wired into the WPI_CANTalonSRX_SetParameter.vi

The lower image shows the WPI_CANTalonSRX_SetParameter.vi block diagram and As we saw in the original issue with the example it also scales the "Value" input to "Native Units" 

So regardless if the user wires rotations or native units into the "New Sensor Positon" the wrong value will be set as the sensor position due to this unintended double conversion.

It appears that the Value input for the WPI_CANTalonSRX_SetParameter.vi was originally designed to be in native units and someone added the conversion not realizing how it would affect the other vis that use it.

As I tried to explain before the units (native or rotation) for the Sensor position inputs is confusing. So much so that even the driver and example developer had difficulty. This is why I recommended that the unit type (Native or Rotation) be stated in the Enum selection.

Since we are now referring to a problem with the WPI driver this may not be the ideal location to post this issue. If there is a better location please let me know and I will post there as well

**Comment by ozrien** [comment]
The LabVIEW position example works as advertised [just retested the position seeding].  The purpose of this repository is to hold functional-out-of-the-box examples with the FRC2016 tool-suite.  The position example appears to function correctly, therefore no changes need to be done to this repository.

Yes, there are limitations in the FRC2016 tool-suite which you have pointed out.  All of them are addressed and worked-around in the examples in this repository, and are also documented in section 21.25.  

When these limitations are fixed in the FRC2017 release, this repository will likely be updated to match it.  These limitations are already known and documented privately.

The reason setting the sensor position must be in native units is because although the scalar VI is called in the Set-Pos.vi, it's input feedback device signal is left un-wired, defaulting to quadrature encoder and therefore having a scalar of '1', assuming configEncoderCpr is not called.  

I did however notice a copy/paste documentation bug in section 21.25 of the Talon SRX reference manual, so I released an update [today](http://www.ctr-electronics.com/talon-srx.html#product_tabs_technical_resources).
